### ISSUE TITLE
Rebuild Image on Original Repo Changes

### ISSUE THREAD

**Issue by jiahuif** [toksaitov/neural-doodle-gpu#1]
The image should be rebuilt every time the original repo changes. Web hooks may be needed.

**Comment by jiahuif** [comment]
Solved by adding offical docker support.
Thank you for your effort!

**Comment by toksaitov** [comment]
@IndeedPlusPlus
Will add it at some point. Thank you for your effort adding the official Docker support to the neural-doodle project!
